FROM arm64v8/debian

RUN apt-get update

RUN apt-get install curl -y

RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -E

RUN apt-get install -y nodejs

COPY ./@types /nodular/@types
COPY ./nodular /nodular/nodular
COPY ./nodular-server /nodular/nodular-server

RUN npm i typescript -g

WORKDIR /nodular/nodular
RUN npm i
RUN tsc -p ./src

WORKDIR /nodular/nodular-server
RUN npm i
RUN tsc -p ./src