FROM arm64v8/debian

RUN apt-get update

RUN apt-get install curl

RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -E

RUN apt-get install -y nodejs

COPY ./@types /@types
COPY ./nodular /nodular
COPY ./nodular-server /nodular-server

RUN npm i typescript -g

WORKDIR /nodular
RUN npm i
RUN tsc -p ./src

WORKDIR /nodular-server
RUN npm i
RUN tsc -p ./src